### ISSUE TITLE
Extension never activates

### ISSUE THREAD

**Issue by katettudelft** [lovebirdsx/better-comments-enhanced#2]
Hello!

Love the app idea, I have been wanting highlighting for markdown code fragments.

Unfortunately, the extension never starts. I checked the logs and got this error:

```js
2024-07-24 11:19:12.927 [error] Activating extension lovebird.better-comments-enhanced failed due to an error:
2024-07-24 11:19:12.927 [error] TypeError: item.tag.replace is not a function
	at Parser.setTags (c:\Users\katettudelft\.vscode\extensions\lovebird.better-comments-enhanced-1.0.3\out\parser.js:306:46)
	at new Parser (c:\Users\katettudelft\.vscode\extensions\lovebird.better-comments-enhanced-1.0.3\out\parser.js:283:14)
	at c:\Users\katettudelft\.vscode\extensions\lovebird.better-comments-enhanced-1.0.3\out\extension.js:21:22
	at Generator.next (<anonymous>)
	at c:\Users\katettudelft\.vscode\extensions\lovebird.better-comments-enhanced-1.0.3\out\extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\katettudelft\.vscode\extensions\lovebird.better-comments-enhanced-1.0.3\out\extension.js:4:12)
	at activate (c:\Users\katettudelft\.vscode\extensions\lovebird.better-comments-enhanced-1.0.3\out\extension.js:18:12)
	at K.kb (c:\Users\katettudelft\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:13532)
	at K.jb (c:\Users\katettudelft\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:13245)
	at c:\Users\katettudelft\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:11246
	at async c.n (c:\Users\katettudelft\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6384)
	at async c.m (c:\Users\katettudelft\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6347)
	at async c.l (c:\Users\katettudelft\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5804)
```

This is on a windows 10 machine, with the latest vscode version available.

Please let me know if you need any more info!

**Comment by lovebirdsx** [comment]
What version of vscode are you using, can you build a minimal test project to help me locate the issue?

**Comment by beedell-roke** [comment]
@lovebirdsx, *my* minimal test case is merely `* ! s`, which it does not appear to colourise:

<p></p><img width="1278" height="538" alt="Image" src="https://github.com/user-attachments/assets/f8721842-a963-4350-8806-2325feba4dbf" /><p></p>

However, I've no failure logs. I've been watching this issue since 2024.

#### My Environment

<blockquote>

~~~YAML
Version: 1.122.0-insider
Commit: 183159e2b33bd31518b95c8a06372ff56645556f
Date: 2026-05-26T04:28:27Z
Electron: 39.8.8
ElectronBuildId: 13870025
Chromium: 142.0.7444.265
Node.js: 22.22.1
V8: 14.2.231.22-electron.0
OS: Linux x64 7.0.9-205.fc44.x86_64
~~~

</blockquote>

**Comment by lovebirdsx** [comment]
Add follow settings to your workspace settings.json, and open a markdown file, input `* ! s`, check if it‘s ok.
``` json
    "better-comments.highlightMarkdown": true,
    "better-comments.tags": [
        {
            "tag": "!",
            "color": "#FF2D00",
            "strikethrough": false,
            "underline": false,
            "backgroundColor": "transparent",
            "bold": false,
            "italic": false
        },
        {
            "tag": "?",
            "color": "#3498DB",
            "strikethrough": false,
            "underline": false,
            "backgroundColor": "transparent",
            "bold": false,
            "italic": false
        },
        {
            "tag": "//",
            "color": "#474747",
            "strikethrough": true,
            "underline": false,
            "backgroundColor": "transparent",
            "bold": false,
            "italic": false
        },
        {
            "tag": "todo",
            "color": "#FF8C00",
            "strikethrough": false,
            "underline": false,
            "backgroundColor": "transparent",
            "bold": false,
            "italic": false
        },
        {
            "tag": "*",
            "color": "#98C379",
            "strikethrough": false,
            "underline": false,
            "backgroundColor": "transparent",
            "bold": false,
            "italic": false
        }
    ]
```

**Comment by beedell-roke** [comment]
@lovebirdsx, thanks, and apologies. I didn't realise that that was required; rather, I'd presumed that the `README` was explaining how to customise it. Some defaults might be useful.
